### ISSUE TITLE
Could not find symbol named: #createDspFromBoxes searching in module: 'librariesBundle/libdynamic-engine.dylib'

### ISSUE THREAD

**Issue by luque** [lucretiomsp/phausto#23]
After installing Phausto on Pharo 12 and unpacking `librariesBundle_mac_intel.zip` in the Pharo image directory, when I execute the Hello Phausto example from README:

```
"create a Sine wave Oscillator"
sine := SineOsc new.
"creates a stereo DSP from the Oscillator"
dsp := sine stereo asDsp.
"initialize the DSP"
dsp init.
"start the sound"
dsp start.
"stop the sound"
dsp stop.
"destroy the dsp when you no longer need it"
dsp destroy.
```

I get the Exception `Could not find symbol named: #createDspFromBoxes searching in module: 'librariesBundle/libdynamic-engine.dylib'`.

**Comment by lucretiomsp** [comment]
Hello Luque, 
I understand why you get this error and it will be fixed as soon as possible as first we have to recompile libfaust fro new features related with cmajor.

in the meanwhile you can go to the librariesBundle folder and double click on all the dylib.files one by one.
you will get a security warning. you go to security and privacy on your ac and you authorize the lib.
then you restart the image and it should work.
if you dont succed I will upload a few screenshots with the processs.
sorry for the incovenience
d

**Comment by luque** [comment]
Thank you!

I've tried your workaround, however it does not work in my case. When I double-click on the *.dylib files the Console is opened and show an error "cannot execute binary file".

Maybe I should open these files with other application?

**Comment by luque** [comment]
All examples are already working in Pharo 12. 

The problem was a I was copying the libraries to my Pharo image directory. Once I have copied them to the VM's library directory (i.e. in Mac OS to my `pharo-vm/Pharo.app/Contents/MacOS/Plugins/` directory) it has worked like a charm.

Thank you!
