### ISSUE TITLE
dsp>>displayUI fails

### ISSUE THREAD

**Issue by luque** [lucretiomsp/phausto#24]
I'm trying the examples with Pharo 12 and the `dsp>>displayUI` method fails because `BlElement>>fromDictionary:forDsp:`  is not implemented.
<img width="677" alt="Captura de pantalla 2024-09-12 a las 23 16 01" src="https://github.com/user-attachments/assets/0cc7b2b6-0172-456c-9a0a-ced9a994c719">

**Comment by lucretiomsp** [comment]
Sorry, my fault.
You need this package too:

Metacello new

 baseline: 'CoypuIDE';

 repository: 'github://pharo-graphics/CoypuIDE/';

 onConflict: [ :ex | ex useIncoming ];

 onUpgrade: [ :ex | ex useIncoming ];

 load.


That would be included in Phausto baseline with the next update.


Peace.

D

**Comment by luque** [comment]
Thank you, Domenico!

However, it still fails because it seems the method is not implemented in `BlElement`.

This is the example I'm trying: 
<img width="1327" alt="Captura de pantalla 2024-09-13 a las 11 23 08" src="https://github.com/user-attachments/assets/33879038-4f0b-4f39-967e-4eeafc21aaf1">

**Comment by luque** [comment]
Hi D,

It's working. It seems it requires also to load the CoypuIDE project from `github://pharo-graphics/CoypuIDE/`.

Thank you!

**Comment by lucretiomsp** [comment]
Okok, thanks for letting me know. I will check what's the problem as soon
as I am back to my computer next Monday.
Thanks for letting me lnow

**Comment by lucretiomsp** [comment]
Great. Yes, I have to fix the baseline ;)
