### ISSUE TITLE
GToolkit support

### ISSUE THREAD

**Issue by luque** [lucretiomsp/phausto#25]
I'd like to use Phausto on Glamorous Toolkit. I understand there are important differences between GT and Pharo, like the graphical stack, so maybe I could not use the graphical representations. However, I expected the FFI integration with the native libraries could be potentially reused on GT.

I've installed Phausto on GT and tried with the following example. The Sine object is instantiated successfully (so the libfaust integration works), but it fails invoking the libdynamic-engine library, as you can see in the following snapshot: 
<img width="834" alt="Captura de pantalla 2024-09-13 a las 17 31 47" src="https://github.com/user-attachments/assets/62a47dc4-4b40-4c23-aa17-72d39a24e633">

**Comment by lucretiomsp** [comment]
Hello Raphael. I am working with Pharo 12. Phausto is designed and tested for Pharo. I don't know how FFI works in GToolkit.
